site_name: Wcowin的个人网站
site_url: https://wcowin.github.io/mymkdocs/
theme:
  name: material
  icon:
    tag:
      <identifier>: octicons/tag-16
  features:
    - navigation.instant
    #- header.autohide  #自动隐藏
    - announce.dismiss #忘了
    - navigation.tracking #也忘了
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - navigation.expand
  language: zh # 一些提示性的文字会变成中文


  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    ##material/brightness-7+material/brightness-4

  font:
    text: Roboto
  features:
    - navigation.instant

nav: 
  - 主页: index.md
  - 博客:
    - Python: blog/index.md
    - C语言: blog/c.md
  - 旅行: 
    - 重庆: trip/travel.md
  - 关于:
    - 个人履历: about/geren.md
  
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  #表情
  - md_in_html
plugins:
  - glightbox
  
copyright: Copyright &copy; 2022王科文 # 左下角的版权声明
  

extra:
  version:
    provider: 1.0
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/Wcowin
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1135801806@qq.com> #联系方式
#cookie 
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
      如果你同意,你可以帮助我们让我们的网站更好 ,
      比如：
      王科文是帅哥～
    #描述
      
plugins:
  - search
  - tags:
      tags_file: tags.md  #标签
